# ASIC Dynamic First Glance

Load the raw ASIC dynamic files, compare schemas across hospitals, apply the shared translation map, inspect key value checks, and review a first harmonized dynamic view.

In [1]:
from pathlib import Path
import sys

import pandas as pd

try:
    from IPython.display import Markdown, display
except ImportError:
    def display(obj):
        print(obj)

    def Markdown(text):
        return text


def find_repo_root(start=None):
    start = (start or Path.cwd()).resolve()
    for candidate in [start, *start.parents]:
        if (candidate / "src" / "icu_data_platform").exists():
            return candidate
    raise FileNotFoundError("Could not find repo root containing src/icu_data_platform")


REPO_ROOT = find_repo_root()
SRC_DIR = REPO_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from icu_data_platform.sources.asic.qc.dynamic_checks import (
    DEFAULT_DYNAMIC_DATA_DIR,
    DEFAULT_TRANSLATION_PATH,
    build_canonical_to_raw,
    build_harmonized_dynamic_table,
    find_non_numeric_value_issues,
    flag_cross_hospital_distribution_issues,
    load_dynamic_tables,
    load_dynamic_translation,
    normalize_missing,
    numeric_distribution_summary,
)

RAW_DYNAMIC_DIR = DEFAULT_DYNAMIC_DATA_DIR
TRANSLATION_PATH = DEFAULT_TRANSLATION_PATH
RAW_DYNAMIC_DIR, TRANSLATION_PATH

(PosixPath('/Users/joanameyer/data/asic/raw_sample10'),
 PosixPath('/Users/joanameyer/repository/icu-data-platform/src/icu_data_platform/sources/asic/column_translation.json'))

In [2]:
def empty_columns(df):
    return [column for column in df.columns if normalize_missing(df[column]).isna().all()]


def example_values(series, max_values=8):
    normalized = normalize_missing(series)
    unique_values = normalized.dropna().astype(str).unique().tolist()
    preview = unique_values[:max_values]
    if len(unique_values) > max_values:
        preview.append("...")
    return preview


def value_preview(df, max_values=8):
    rows = []
    for column in df.columns:
        normalized = normalize_missing(df[column])
        non_null = normalized.dropna()
        rows.append(
            {
                "column": column,
                "dtype": str(df[column].dtype),
                "non_null_count": int(non_null.shape[0]),
                "n_unique_non_null": int(non_null.nunique()),
                "example_values": example_values(df[column], max_values=max_values),
            }
        )
    return pd.DataFrame(rows)


def numeric_summary(series):
    numeric = pd.to_numeric(series, errors="coerce").dropna()
    if numeric.empty:
        return {
            "n": 0,
            "min": pd.NA,
            "q1": pd.NA,
            "median": pd.NA,
            "q3": pd.NA,
            "max": pd.NA,
            "iqr": pd.NA,
            "example_values": [],
        }
    q1 = numeric.quantile(0.25)
    q3 = numeric.quantile(0.75)
    return {
        "n": int(numeric.shape[0]),
        "min": float(numeric.min()),
        "q1": float(q1),
        "median": float(numeric.median()),
        "q3": float(q3),
        "max": float(numeric.max()),
        "iqr": float(q3 - q1),
        "example_values": numeric.unique()[:10].tolist(),
    }

## Raw Dynamic Files

Load all hospital-level ASIC dynamic CSV files and inspect the raw dataset shape.

In [3]:
dynamic_tables = load_dynamic_tables(RAW_DYNAMIC_DIR)
dynamic_translation = load_dynamic_translation(TRANSLATION_PATH)
canonical_to_raw = build_canonical_to_raw(dynamic_translation)

dataset_overview = pd.DataFrame(
    [
        {
            "hospital": hospital,
            "rows": df.shape[0],
            "columns": df.shape[1],
            "empty_columns": len(empty_columns(df)),
        }
        for hospital, df in dynamic_tables.items()
    ]
).sort_values("hospital").reset_index(drop=True)

display(dataset_overview)

    hospital   rows  columns  empty_columns
0  asic_UK00  11656      106             42
1  asic_UK02  19297       85             15
2  asic_UK03  21942      105             44
3  asic_UK04  12684       74             10
4  asic_UK06  10808      105             98
5  asic_UK07  20455      106             22
6  asic_UK08   4805      105             46

## Raw Schema Comparison

Compare raw columns across hospitals using the first hospital file as the reference.

In [4]:
reference_hospital = next(iter(dynamic_tables))
reference_columns = list(dynamic_tables[reference_hospital].columns)
reference_set = set(reference_columns)

schema_rows = []
column_sets = [set(df.columns) for df in dynamic_tables.values()]
common_columns = sorted(set.intersection(*column_sets))
all_columns = sorted(set.union(*column_sets))

for hospital, df in dynamic_tables.items():
    columns = list(df.columns)
    column_set = set(columns)
    schema_rows.append(
        {
            "hospital": hospital,
            "same_column_order_as_reference": columns == reference_columns,
            "same_column_set_as_reference": column_set == reference_set,
            "missing_vs_reference": sorted(reference_set - column_set),
            "extra_vs_reference": sorted(column_set - reference_set),
        }
    )

display(pd.DataFrame(schema_rows).sort_values("hospital").reset_index(drop=True))
print(f"Reference hospital: {reference_hospital}")
print(f"Columns common to all hospitals ({len(common_columns)}):")
print(common_columns)
print()
print(f"Columns appearing in at least one hospital ({len(all_columns)}):")
print(all_columns)

,hospital,same_column_order_as_reference,same_column_set_as_reference,missing_vs_reference,extra_vs_reference
0,asic_UK00,True,True,[],[]
1,asic_UK02,False,False,"[AF_spontan, BNP, Bilirubin_ges., CK, DPAP, De...","[Creatinkinase, ECMO_FiO2, Interleukin_6, Koer..."
2,asic_UK03,False,False,[ARDS_Diagnose_App],[]
3,asic_UK04,False,False,"[Clonidin_intravenoes_kontinuierlich, Dexameth...",[Pseudo-ID]
4,asic_UK06,False,False,"[SOFA, Vt]",[Organversagen:_SOFA_Score_ohne_GCS]
5,asic_UK07,False,False,[SOFA],[Organversagen:_SOFA_Score_ohne_GCS]
6,asic_UK08,False,False,"[SOFA, Vt]",[Organversagen:_SOFA_Score_ohne_GCS]

Reference hospital: asic_UK00
Columns common to all hospitals (56):
['24h-Bilanz_(Fluessigkeiten-Einfuhr_vs_-Ausfuhr)', 'AF', 'Albumin', 'Amylase', 'BE_arteriell', 'Bicarbonat_arteriell', 'CK-MB', 'CRP', 'Compliance', 'D-Dimere', 'DAP', 'EVLWI', 'FeO2', 'FiO2', 'GEDVI', 'GOT', 'GPT', 'HF', 'HI_(Bolus)', 'HI_(kontinuierlich)', 'HZV_(Bolus)', 'Haematokrit', 'Haemoglobin', 'Harnstoff', 'Horowitz-Quotient_(ohne_Temp-Korrektur)', 'I:E', 'INR', 'Kreatinin', 'LDH', 'Lagerungstherapie', 'Laktat_arteriell', 'Leukozyten', 'Lipase', 'MAP', 'NT-pro_BNP', 'PCT', 'PEEP', 'P_EI', 'PseudoID', 'SAP', 'SVRI', 'SV_(Bolus)', 'SpO2', 'SzvO2', 'Thrombozyten', 'Time', 'Troponin', 'ZVD', 'Zeit_ab_Aufnahme', 'deltaP', 'etCO2', 'individuelles_Tidalvolumen_pro_kg_idealem_Koerpergewicht', 'pH_arteriell', 'pTT', 'paCO2_(ohne_Temp-Korrektur)', 'paO2_(ohne_Temp-Korrektur)']

Columns appearing in at least one hospital (114):
['24h-Bilanz_(Fluessigkeiten-Einfuhr_vs_-Ausfuhr)', 'AF', 'AF_spontan', 'ARDS_Diagnose_App', 'Albumin', 'Amylase', 'BE_arteriell', 'BNP', 'Bicarbonat_arteriell', 'Bilirubin_ges.', 'CK', 'CK-MB', 'CRP', 'Clonidin_intravenoes_kontinuierlich', 'Compliance', 'Creatinkinase', 'D-Dimere', 'DAP', 'DPAP', 'Dexamethason_intravenoes_bolusweise', 'Dexmedetomidin_intravenoes_kontinuierlich', 'Dobutamin_intravenoes_kontinuierlich', 'ECMO', 'ECMO_FiO2', 'EVLWI', 'Epinephrin_intravenoes_kontinuierlich', 'Extrakorporaler_Blutfluss', 'Extrakorporaler_Gasfluss_(O2)', 'FeO2', 'Fentanyl_intravenoes_kontinuierlich', 'FiO2', 'Fludrocortison_peroral_bolusweise', 'Furosemid_intravenoes_kontinuierlich', 'GEDVI', 'GOT', 'GPT', 'Gaszusammensetzung_(%O2)', 'HF', 'HI_(Bolus)', 'HI_(kontinuierlich)', 'HZV_(Bolus)', 'HZV_(kontinuierlich)', 'Haematokrit', 'Haemoglobin', 'Harnstoff', 'Horowitz-Quotient_(ohne_Temp-Korrektur)', 'Hydrocortison_intravenoes_bolusweise', 'I:E', 'IL-6', 'INR', 'Inhalatives_Iloprost', 'Inhalatives_NO', 'Interleukin_6', 'Isofluran_inhalativ', 'Ketanest_intravenoes_kontinuierlich', 'Koerperkerntemperatur', 'Koerpertemperatur', 'Kreatinin', 'LDH', 'Lagerungstherapie', 'Laktat_arteriell', 'Leukozyten', 'Levosimendan_intravenoes_kontinuierlich', 'Lipase', 'Lymphocyten', 'Lymphozyten_absolut', 'Lymphozyten_prozentual', 'MAP', 'MPAP', 'Midazolam_intravenoes_kontinuierlich', 'Milrinon_intravenoes_kontinuierlich', 'Morphin_intravenoes_kontinuierlich', 'NT-proBNP', 'NT-pro_BNP', 'Norepinephrin_intravenoes_kontinuierlich', 'Organversagen:_SOFA_Score_ohne_GCS', 'PCT', 'PCWP', 'PEEP', 'PVRI', 'P_EI', 'Prednisolon_intravenoes_bolusweise', 'Propofol_intravenoes_kontinuierlich', 'Pseudo-ID', 'PseudoID', 'Rocuronium_intravenoes_bolusweise', 'SAP', 'SOFA', 'SPAP', 'SVI_(Bolus)', 'SVI_(kontinuierlich)', 'SVRI', 'SV_(Bolus)', 'SV_(kontinuierlich)', 'SaO2', 'Sevofluran_inhalativ', 'SpO2', 'Sufentanil_intravenoes_kontinuierlich', 'SzvO2', 'Terlipressin_intravenoes_bolusweise', 'Thrombozyten', 'Time', 'Troponin', 'Vasopressin_intravenoes_kontinuierlich', 'Vt', 'ZVD', 'Zeit_ab_Aufnahme', 'deltaP', 'etCO2', 'individuelles_Tidalvolumen_pro_kg_idealem_Koerpergewicht', 'pH_arteriell', 'pTT', 'paCO2_(ohne_Temp-Korrektur)', 'paO2_(ohne_Temp-Korrektur)']

## Translation Coverage

Apply the shared ASIC translation map and show any raw columns that are still intentionally untranslated.

In [5]:
raw_dynamic_columns = sorted(set().union(*[set(df.columns) for df in dynamic_tables.values()]))
mapped_translation_keys = sorted(dynamic_translation.keys())
unmapped_raw_columns = sorted(set(raw_dynamic_columns) - set(mapped_translation_keys))
extra_translation_keys = sorted(set(mapped_translation_keys) - set(raw_dynamic_columns))

display(
    pd.DataFrame(
        [
            {
                "raw_dynamic_columns": len(raw_dynamic_columns),
                "mapped_translation_keys": len(mapped_translation_keys),
                "unmapped_raw_columns": unmapped_raw_columns,
                "extra_translation_keys": extra_translation_keys,
            }
        ]
    )
)

if unmapped_raw_columns:
    print("Dropped raw dynamic columns (currently not translated):")
    print(unmapped_raw_columns)

translation_df = pd.DataFrame(
    [
        {"raw_column": raw_column, "canonical_name": canonical_name}
        for raw_column, canonical_name in sorted(dynamic_translation.items(), key=lambda item: (item[1], item[0]))
    ]
)
display(translation_df)

,raw_dynamic_columns,mapped_translation_keys,unmapped_raw_columns,extra_translation_keys
0,114,113,[ARDS_Diagnose_App],[]

Dropped raw dynamic columns (currently not translated):
['ARDS_Diagnose_App']

                                            raw_column       canonical_name
0                                              Albumin              albumin
1                                                  GPT                  alt
2                                              Amylase              amylase
3                                                  GOT                  ast
4                                         BE_arteriell      base_excess_art
..                                                 ...                  ...
108                                          Harnstoff                 urea
109             Vasopressin_intravenoes_kontinuierlich  vasopressin_iv_cont
110                                                 Vt                   vt
111  individuelles_Tidalvolumen_pro_kg_idealem_Koer...        vt_per_kg_ibw
112                                         Leukozyten                  wbc

[113 rows x 2 columns]

## ECMO vs ECMO_FiO2

Check whether the raw `ECMO` indicator and `ECMO_FiO2` behave like the same variable or not.

In [6]:
ecmo_rows = []
for hospital, df in dynamic_tables.items():
    ecmo = pd.to_numeric(df["ECMO"], errors="coerce") if "ECMO" in df.columns else pd.Series(dtype="float64")
    ecmo_fio2 = pd.to_numeric(df["ECMO_FiO2"], errors="coerce") if "ECMO_FiO2" in df.columns else pd.Series(dtype="float64")

    row = {
        "hospital": hospital,
        "has_ecmo": "ECMO" in df.columns,
        "has_ecmo_fio2": "ECMO_FiO2" in df.columns,
        "ecmo_non_null": int(ecmo.notna().sum()) if "ECMO" in df.columns else 0,
        "ecmo_values": sorted(pd.Series(ecmo.dropna().unique()).astype(float).tolist())[:10] if "ECMO" in df.columns else [],
        "ecmo_fio2_non_null": int(ecmo_fio2.notna().sum()) if "ECMO_FiO2" in df.columns else 0,
        "ecmo_fio2_values": sorted(pd.Series(ecmo_fio2.dropna().unique()).astype(float).tolist())[:10] if "ECMO_FiO2" in df.columns else [],
    }

    if "ECMO" in df.columns and "ECMO_FiO2" in df.columns:
        overlap = ecmo.notna() & ecmo_fio2.notna()
        row["rows_with_both_non_null"] = int(overlap.sum())
        row["rows_ecmo1_and_fio2_non_null"] = int(((ecmo == 1) & ecmo_fio2.notna()).sum())
        row["rows_ecmo0_and_fio2_non_null"] = int(((ecmo == 0) & ecmo_fio2.notna()).sum())
    else:
        row["rows_with_both_non_null"] = 0
        row["rows_ecmo1_and_fio2_non_null"] = 0
        row["rows_ecmo0_and_fio2_non_null"] = 0

    ecmo_rows.append(row)

display(pd.DataFrame(ecmo_rows).sort_values("hospital").reset_index(drop=True))

for hospital, df in dynamic_tables.items():
    if "ECMO" in df.columns and "ECMO_FiO2" in df.columns:
        ecmo = pd.to_numeric(df["ECMO"], errors="coerce")
        ecmo_fio2 = pd.to_numeric(df["ECMO_FiO2"], errors="coerce")
        overlap = ecmo.notna() & ecmo_fio2.notna()
        display(Markdown(f"### {hospital}"))
        if overlap.any():
            display(pd.crosstab(ecmo[overlap], ecmo_fio2[overlap]))
        else:
            print("No overlapping non-null ECMO and ECMO_FiO2 rows.")

,hospital,has_ecmo,has_ecmo_fio2,ecmo_non_null,ecmo_values,ecmo_fio2_non_null,ecmo_fio2_values,rows_with_both_non_null,rows_ecmo1_and_fio2_non_null,rows_ecmo0_and_fio2_non_null
0,asic_UK00,True,False,10096,[0.0],0,[],0,0,0
1,asic_UK02,True,True,6216,"[0.0, 1.0]",617,"[1.0, 21.0, 100.0]",617,617,0
2,asic_UK03,True,False,512,"[0.0, 1.0]",0,[],0,0,0
3,asic_UK04,False,False,0,[],0,[],0,0,0
4,asic_UK06,True,False,0,[],0,[],0,0,0
5,asic_UK07,True,False,3432,"[0.0, 1.0]",0,[],0,0,0
6,asic_UK08,True,False,0,[],0,[],0,0,0

### asic_UK02

ECMO_FiO2  1.0    21.0   100.0
ECMO
1.0           35      2    580

## Theme Groups

Order the translated dynamic columns by broad clinical families.

In [7]:
THEME_GROUPS = {
    "id_time": [
        "hospital_id",
        "stay_id",
        "time",
        "minutes_since_admit",
    ],
    "vitals": [
        "heart_rate",
        "sbp",
        "map",
        "dbp",
        "resp_rate",
        "spont_resp_rate",
        "core_temp",
        "spo2",
        "sao2",
        "scvo2",
        "cvp",
    ],
    "ventilation": [
        "fio2",
        "feo2",
        "peep",
        "delta_p",
        "insp_pressure",
        "compliance",
        "ie_ratio",
        "vt",
        "vt_per_kg_ibw",
        "etco2",
        "pf_ratio",
    ],
    "blood_gas": [
        "pao2",
        "paco2",
        "ph_art",
        "bicarbonate_art",
        "base_excess_art",
        "lactate_art",
    ],
    "hemodynamics": [
        "pap_sys",
        "pap_mean",
        "pap_dias",
        "pcwp",
        "cardiac_output_bolus",
        "cardiac_output_cont",
        "cardiac_index_bolus",
        "cardiac_index_cont",
        "stroke_volume_bolus",
        "stroke_volume_cont",
        "stroke_index_bolus",
        "stroke_index_cont",
        "svri",
        "pvri",
        "gedvi",
        "evlwi",
    ],
    "hematology_coag": [
        "hemoglobin",
        "hematocrit",
        "wbc",
        "platelets",
        "lymph_abs",
        "lymph_pct",
        "inr",
        "ptt",
        "d_dimer",
    ],
    "chemistry_inflammation": [
        "albumin",
        "crp",
        "pct",
        "il6",
        "bilirubin_total",
        "urea",
        "creatinine",
        "bnp",
        "ntprobnp",
        "ast",
        "alt",
        "ldh",
        "amylase",
        "lipase",
        "troponin",
        "ck",
        "ck_mb",
    ],
    "support_therapy": [
        "fluid_balance_24h",
        "position_therapy",
        "ecmo",
        "ecmo_o2",
        "extracorp_blood_flow",
        "extracorp_o2_flow",
        "inhaled_no",
        "inhaled_iloprost",
    ],
    "vasoactive_inotrope": [
        "dobutamine_iv_cont",
        "epinephrine_iv_cont",
        "norepinephrine_iv_cont",
        "vasopressin_iv_cont",
        "milrinone_iv_cont",
        "levosimendan_iv_cont",
        "terlipressin_iv_bolus",
    ],
    "sedation_analgesia": [
        "propofol_iv_cont",
        "midazolam_iv_cont",
        "clonidine_iv_cont",
        "dexmedetomidine_iv_cont",
        "ketanest_iv_cont",
        "isoflurane_inh",
        "sevoflurane_inh",
        "sufentanil_iv_cont",
        "fentanyl_iv_cont",
        "morphine_iv_cont",
        "rocuronium_iv_bolus",
    ],
    "other_meds": [
        "furosemide_iv_cont",
        "hydrocortisone_iv_bolus",
        "prednisolone_iv_bolus",
        "dexamethasone_iv_bolus",
        "fludrocortisone_po_bolus",
    ],
    "scores": [
        "sofa",
    ],
}

canonical_dynamic_columns = sorted(set(dynamic_translation.values()))
assigned_columns = [column for columns in THEME_GROUPS.values() for column in columns]
unassigned_canonical_columns = sorted(set(canonical_dynamic_columns) - set(assigned_columns))

ordered_canonical_columns = []
for theme_columns in THEME_GROUPS.values():
    for column in theme_columns:
        if column == "hospital_id" or column in canonical_dynamic_columns:
            ordered_canonical_columns.append(column)

theme_rows = [{"theme": theme, "columns": columns} for theme, columns in THEME_GROUPS.items()]
display(pd.DataFrame(theme_rows))
print("Unassigned canonical columns:", unassigned_canonical_columns)

                     theme                                            columns
0                  id_time  [hospital_id, stay_id, time, minutes_since_admit]
1                   vitals  [heart_rate, sbp, map, dbp, resp_rate, spont_r...
2              ventilation  [fio2, feo2, peep, delta_p, insp_pressure, com...
3                blood_gas  [pao2, paco2, ph_art, bicarbonate_art, base_ex...
4             hemodynamics  [pap_sys, pap_mean, pap_dias, pcwp, cardiac_ou...
5          hematology_coag  [hemoglobin, hematocrit, wbc, platelets, lymph...
6   chemistry_inflammation  [albumin, crp, pct, il6, bilirubin_total, urea...
7          support_therapy  [fluid_balance_24h, position_therapy, ecmo, ec...
8      vasoactive_inotrope  [dobutamine_iv_cont, epinephrine_iv_cont, nore...
9       sedation_analgesia  [propofol_iv_cont, midazolam_iv_cont, clonidin...
10              other_meds  [furosemide_iv_cont, hydrocortisone_iv_bolus, ...
11                  scores                                             [sofa]

Unassigned canonical columns: []

## Draft Harmonized Dynamic View

Build one harmonized table per hospital using the translation file, keep the `UK02` `I:E` ratio values, and order columns by theme.

In [8]:
harmonized_tables = {}
source_map_rows = []

for hospital, df in dynamic_tables.items():
    harmonized_df, source_map = build_harmonized_dynamic_table(df, hospital, dynamic_translation)
    harmonized_df = harmonized_df[[column for column in ordered_canonical_columns if column in harmonized_df.columns]].copy()
    harmonized_df["stay_id"] = pd.to_numeric(harmonized_df["stay_id"], errors="coerce").astype("Int64")
    harmonized_tables[hospital] = harmonized_df

    for canonical_name in harmonized_df.columns:
        source_map_rows.append(
            {
                "hospital": hospital,
                "canonical_name": canonical_name,
                "raw_source_columns_used": source_map.get(canonical_name, []),
            }
        )

source_map_df = pd.DataFrame(source_map_rows)
combined_harmonized_df = pd.concat(harmonized_tables.values(), ignore_index=True)

display(source_map_df.head(60))
display(combined_harmonized_df.head())

/var/folders/h3/6lrwxtp942d5w3h70w3y31z40000gp/T/ipykernel_4227/1997355555.py:20: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_harmonized_df = pd.concat(harmonized_tables.values(), ignore_index=True)

,hospital,canonical_name,raw_source_columns_used
0,asic_UK00,hospital_id,[derived from filename]
1,asic_UK00,stay_id,[PseudoID]
2,asic_UK00,time,[Time]
3,asic_UK00,minutes_since_admit,[Zeit_ab_Aufnahme]
4,asic_UK00,heart_rate,[HF]
5,asic_UK00,sbp,[SAP]
6,asic_UK00,map,[MAP]
7,asic_UK00,dbp,[DAP]
8,asic_UK00,resp_rate,[AF]
9,asic_UK00,spont_resp_rate,[AF_spontan]
10,asic_UK00,core_temp,[Koerperkerntemperatur]
11,asic_UK00,spo2,[SpO2]
12,asic_UK00,sao2,[SaO2]
13,asic_UK00,scvo2,[SzvO2]
14,asic_UK00,cvp,[ZVD]
15,asic_UK00,fio2,[FiO2]
16,asic_UK00,feo2,[FeO2]
17,asic_UK00,peep,[PEEP]
18,asic_UK00,delta_p,[deltaP]
19,asic_UK00,insp_pressure,[P_EI]
20,asic_UK00,compliance,[Compliance]
21,asic_UK00,ie_ratio,[I:E]
22,asic_UK00,vt,[Vt]
23,asic_UK00,vt_per_kg_ibw,[individuelles_Tidalvolumen_pro_kg_idealem_Koe...
24,asic_UK00,etco2,[etCO2]
25,asic_UK00,pf_ratio,[Horowitz-Quotient_(ohne_Temp-Korrektur)]
26,asic_UK00,pao2,[paO2_(ohne_Temp-Korrektur)]
27,asic_UK00,paco2,[paCO2_(ohne_Temp-Korrektur)]
28,asic_UK00,ph_art,[pH_arteriell]
29,asic_UK00,bicarbonate_art,[Bicarbonat_arteriell]
30,asic_UK00,base_excess_art,[BE_arteriell]
31,asic_UK00,lactate_art,[Laktat_arteriell]
32,asic_UK00,pap_sys,[SPAP]
33,asic_UK00,pap_mean,[MPAP]
34,asic_UK00,pap_dias,[DPAP]
35,asic_UK00,pcwp,[PCWP]
36,asic_UK00,cardiac_output_bolus,[HZV_(Bolus)]
37,asic_UK00,cardiac_output_cont,[HZV_(kontinuierlich)]
38,asic_UK00,cardiac_index_bolus,[HI_(Bolus)]
39,asic_UK00,cardiac_index_cont,[HI_(kontinuierlich)]
40,asic_UK00,stroke_volume_bolus,[SV_(Bolus)]
41,asic_UK00,stroke_volume_cont,[SV_(kontinuierlich)]
42,asic_UK00,stroke_index_bolus,[SVI_(Bolus)]
43,asic_UK00,stroke_index_cont,[SVI_(kontinuierlich)]
44,asic_UK00,svri,[SVRI]
45,asic_UK00,pvri,[PVRI]
46,asic_UK00,gedvi,[GEDVI]
47,asic_UK00,evlwi,[EVLWI]
48,asic_UK00,hemoglobin,[Haemoglobin]
49,asic_UK00,hematocrit,[Haematokrit]
50,asic_UK00,wbc,[Leukozyten]
51,asic_UK00,platelets,[Thrombozyten]
52,asic_UK00,lymph_abs,[Lymphozyten_absolut]
53,asic_UK00,lymph_pct,[Lymphozyten_prozentual]
54,asic_UK00,inr,[INR]
55,asic_UK00,ptt,[pTT]
56,asic_UK00,d_dimer,[D-Dimere]
57,asic_UK00,albumin,[Albumin]
58,asic_UK00,crp,[CRP]
59,asic_UK00,pct,[PCT]

,hospital_id,stay_id,time,minutes_since_admit,heart_rate,sbp,map,dbp,resp_rate,spont_resp_rate,...,sufentanil_iv_cont,fentanyl_iv_cont,morphine_iv_cont,rocuronium_iv_bolus,furosemide_iv_cont,hydrocortisone_iv_bolus,prednisolone_iv_bolus,dexamethasone_iv_bolus,fludrocortisone_po_bolus,sofa
0,asic_UK00,372,0 days 00:00:00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN
1,asic_UK00,372,0 days 00:15:00,15.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN
2,asic_UK00,372,0 days 00:30:00,30.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN
3,asic_UK00,372,0 days 00:45:00,45.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN
4,asic_UK00,372,0 days 01:00:00,60.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN

In [9]:
schema_summary = pd.DataFrame(
    [
        {
            "hospital": hospital,
            "rows": df.shape[0],
            "canonical_columns": df.shape[1],
            "empty_columns": empty_columns(df),
        }
        for hospital, df in harmonized_tables.items()
    ]
).sort_values("hospital").reset_index(drop=True)
display(schema_summary)

source_map_by_theme = source_map_df.merge(
    pd.DataFrame(
        [
            {"theme": theme, "canonical_name": canonical_name}
            for theme, columns in THEME_GROUPS.items()
            for canonical_name in columns
        ]
    ),
    how="left",
    on="canonical_name",
)
theme_source_map_display = source_map_by_theme[["theme", "canonical_name", "raw_source_columns_used"]].copy()
theme_source_map_display["raw_source_columns_used"] = theme_source_map_display["raw_source_columns_used"].apply(tuple)
display(theme_source_map_display.drop_duplicates())

,hospital,rows,canonical_columns,empty_columns
0,asic_UK00,11656,106,"[feo2, pap_sys, pap_mean, pap_dias, pcwp, card..."
1,asic_UK02,19297,106,"[spont_resp_rate, sao2, feo2, delta_p, vt, ph_..."
2,asic_UK03,21942,106,"[sbp, map, dbp, feo2, ie_ratio, pap_sys, pap_m..."
3,asic_UK04,12684,106,"[scvo2, feo2, vt, pcwp, cardiac_output_cont, s..."
4,asic_UK06,10808,106,"[heart_rate, sbp, map, dbp, resp_rate, spont_r..."
5,asic_UK07,20455,106,"[feo2, compliance, pcwp, cardiac_output_cont, ..."
6,asic_UK08,4805,106,"[scvo2, cvp, feo2, delta_p, vt, etco2, pcwp, c..."

                  theme            canonical_name   raw_source_columns_used
0               id_time               hospital_id  (derived from filename,)
1               id_time                   stay_id               (PseudoID,)
2               id_time                      time                   (Time,)
3               id_time       minutes_since_admit       (Zeit_ab_Aufnahme,)
4                vitals                heart_rate                     (HF,)
..                  ...                       ...                       ...
416  sedation_analgesia          morphine_iv_cont                        ()
417  sedation_analgesia       rocuronium_iv_bolus                        ()
419          other_meds   hydrocortisone_iv_bolus                        ()
422          other_meds  fludrocortisone_po_bolus                        ()
423              scores                      sofa                        ()

[159 rows x 3 columns]

## Cross-Hospital QC

Surface hospital-column pairs that need a closer look: raw non-numeric values and suspicious cross-hospital distribution mismatches.

In [10]:
non_numeric_issues = find_non_numeric_value_issues(dynamic_tables=dynamic_tables, translation=dynamic_translation)
display(non_numeric_issues)

distribution_summary = numeric_distribution_summary(harmonized_tables, min_non_null=20)
distribution_issues = flag_cross_hospital_distribution_issues(
    distribution_summary,
    min_hospitals=4,
    fence_factor=1.5,
)
display(distribution_issues)

,hospital,raw_column,canonical_name,non_null_count,raw_non_numeric_count,resolved_by_custom_parser_count,unresolved_after_custom_parser_count,non_numeric_examples
0,asic_UK02,I:E,ie_ratio,957,957,957,0,"[1/1.5, 1/2.3, 1/1.4, 1.5/1, 1/1, 1/1.1, 1.1/1..."
1,asic_UK04,Bilirubin_ges.,bilirubin_total,56,5,5,0,[<0.15]
2,asic_UK04,Lymphozyten_absolut,lymph_abs,14,4,4,0,[storniert]
3,asic_UK04,Lymphozyten_prozentual,lymph_pct,14,4,4,0,[storniert]
4,asic_UK04,CRP,crp,148,1,1,0,[<0.1]

,canonical_name,hospital,n,flagged_metrics,min,median,iqr,max,range_width
0,albumin,asic_UK00,57,[max],225.699600,376.166000,120.373120,526.632400,300.932800
1,alt,asic_UK03,212,"[iqr, max, range_width]",6.599000,35.694000,87.885000,6142.976000,6136.377000
2,alt,asic_UK04,60,[min],11.000000,24.500000,39.750000,179.000000,168.000000
3,alt,asic_UK08,25,"[min, iqr]",0.000000,22.000000,18.000000,327.000000,327.000000
4,ast,asic_UK02,181,"[max, range_width]",12.000000,51.590000,75.590000,6180.560000,6168.560000
...,...,...,...,...,...,...,...,...,...
61,sufentanil_iv_cont,asic_UK08,2021,[iqr],0.000000,20.000000,47.470000,74.970000,74.970000
62,troponin,asic_UK02,25,"[min, iqr, max, range_width]",0.020000,0.290000,9.590000,15.080000,15.060000
63,urea,asic_UK08,52,[median],0.000000,22.000000,13.175000,44.100000,44.100000
64,vt_per_kg_ibw,asic_UK00,858,[min],5.822485,6.248122,0.248122,6.496243,0.673758
65,vt_per_kg_ibw,asic_UK06,1909,"[median, iqr, max, range_width]",0.000000,4769.172071,8776.959048,16978.252575,16978.252575

In [11]:
print(distribution_issues.canonical_name.unique())

['albumin' 'alt' 'ast' 'bilirubin_total' 'ck' 'ck_mb' 'clonidine_iv_cont'
 'compliance' 'core_temp' 'creatinine' 'delta_p' 'ecmo' 'etco2' 'fio2'
 'hematocrit' 'hemoglobin' 'ie_ratio' 'inr' 'insp_pressure' 'lactate_art'
 'ldh' 'lipase' 'map' 'minutes_since_admit' 'norepinephrine_iv_cont' 'pct'
 'peep' 'pf_ratio' 'ph_art' 'platelets' 'propofol_iv_cont' 'ptt'
 'resp_rate' 'sao2' 'sbp' 'spo2' 'spont_resp_rate' 'sufentanil_iv_cont'
 'troponin' 'urea' 'vt_per_kg_ibw']

In [12]:
for col in distribution_issues.canonical_name.unique():
    # Display col distributions across hospitals for a specific column of interest, e.g. 'albumin'
    col_summary = []
    for hospital, df in harmonized_tables.items():
        if col in df.columns:
            col_summary.append(numeric_summary(df[col]))
    col_summary_df = pd.DataFrame(col_summary, index=harmonized_tables.keys()).reset_index().rename(columns={"index": "hospital"})
    print(f"Distribution summary for column '{col}':")
    display(col_summary_df)

Distribution summary for column 'albumin':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,57,225.6996,346.07272,376.166,466.44584,526.6324,120.37312,"[496.53912, 315.97944, 511.58576, 466.44584, 4..."
1,asic_UK02,177,0.0,288.89,352.09,424.31,552.21,135.42,"[416.79, 343.06, 281.37, 353.6, 340.05, 296.42..."
2,asic_UK03,123,184.83,292.395,328.755,373.4475,559.035,81.0525,"[490.86, 415.11, 371.175, 193.92, 265.125, 375..."
3,asic_UK04,6,285.886,315.9795,436.3525,522.8705,541.679,206.891,"[511.586, 526.632, 541.679, 300.933, 285.88599..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,154,0.78,359.43,390.585,439.14,555.08,79.71,"[410.15, 405.8, 444.94, 394.21, 442.04, 420.3,..."
6,asic_UK08,8,34607.27,35886.24,36713.805,41829.655,50857.64,5943.415,"[44989.45, 35209.14, 36864.27, 40776.39, 50857..."

Distribution summary for column 'alt':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,133,7.0,21.0,38.0,61.0,130.0,40.0,"[43.0, 38.0, 51.0, 21.0, 18.0, 17.0, 25.0, 24...."
1,asic_UK02,13,15.6,115.78,952.01,1122.98,1451.11,1007.2,"[323.34, 1220.76, 1451.11, 1122.98, 1024.0, 95..."
2,asic_UK03,212,6.599,20.847,35.694,108.732,6142.976,87.885,"[41.993, 40.793, 34.794000000000004, 47.992, 1..."
3,asic_UK04,60,11.0,16.0,24.5,55.75,179.0,39.75,"[22.0, 14.0, 16.0, 12.0, 91.0, 84.0, 50.0, 36...."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,228,6.0,24.0,39.0,58.0,328.0,34.0,"[57.0, 309.0, 328.0, 200.0, 161.0, 138.0, 83.0..."
6,asic_UK08,25,0.0,18.0,22.0,36.0,327.0,18.0,"[47.0, 41.0, 36.0, 38.0, 31.0, 39.0, 21.0, 15...."

Distribution summary for column 'ast':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,138,9.0,31.0,46.0,84.75,356.0,53.75,"[84.0, 82.0, 64.0, 56.0, 29.0, 25.0, 50.0, 42...."
1,asic_UK02,181,12.0,30.59,51.59,106.18,6180.56,75.59,"[37.79, 40.19, 36.59, 163.17, 61.19, 38.39, 32..."
2,asic_UK03,181,7.799,44.393,65.389,109.182,2785.936,64.789,"[65.98899999999999, 245.959, 148.775, 545.309,..."
3,asic_UK04,60,12.0,22.0,29.5,46.25,216.0,24.25,"[22.0, 19.0, 14.0, 12.0, 47.0, 28.0, 32.0, 39...."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,183,15.0,45.0,68.0,129.5,439.0,84.5,"[58.0, 70.0, 123.0, 97.0, 88.0, 69.0, 59.0, 81..."
6,asic_UK08,23,11.0,26.5,38.0,55.5,76.0,29.0,"[56.0, 35.0, 25.0, 34.0, 37.0, 43.0, 38.0, 74...."

Distribution summary for column 'bilirubin_total':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,138,3.078666,7.525628,10.433257,16.889904,85.005389,9.364276,"[8.893924, 4.275925, 5.302147, 5.815258, 4.789..."
1,asic_UK02,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
2,asic_UK03,254,2.7,13.975,69.95,225.65,521.8,211.675,"[5.3, 5.9, 23.2, 45.7, 40.3, 66.3, 5.6, 4.2, 2..."
3,asic_UK04,56,0.0,3.591,5.2155,8.84925,26.676,5.25825,"[2.736, 2.907, 8.379, 23.256, 26.676, 12.483, ..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,238,0.0,3.76,10.52,78.2775,303.53,74.5175,"[9.23, 14.02, 11.97, 7.87, 6.67, 4.45, 6.16, 3..."
6,asic_UK08,9,0.0,6.84,10.26,32.49,46.17,25.65,"[30.78, 10.26, 3.42, 6.84, 0.0, 46.17, 37.62, ..."

Distribution summary for column 'ck':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,191,18.0,77.75,98.0,270.5,2745.0,192.75,"[1315.0, 82.0, 85.0, 1852.0, 91.0, 101.0, 1417..."
1,asic_UK02,70,0.0,35.4,60.0,111.0,14016.6,75.6,"[34.2, 32.4, 31.8, 16.8, 24.0, 492.6, 1224.6, ..."
2,asic_UK03,31,9.598,20.697,62.39,174.271,1308.382,153.574,"[778.67, 683.8860000000002, 238.76, 556.107, 6..."
3,asic_UK04,69,17.0,66.0,148.0,295.0,788.0,229.0,"[48.0, 46.0, 80.0, 144.0, 140.0, 92.0, 576.0, ..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,86,19.0,38.25,85.0,405.75,5818.0,367.5,"[29.0, 318.0, 112.0, 761.0, 1076.0, 1329.0, 98..."
6,asic_UK08,13,39.0,61.0,265.0,724.0,1285.0,663.0,"[521.0, 745.0, 724.0, 63.0, 61.0, 40.0, 417.0,..."

Distribution summary for column 'ck_mb':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,33,9.0,17.0,33.0,68.0,119.0,51.0,"[53.0, 15.0, 17.0, 19.0, 20.0, 16.0, 14.0, 107..."
1,asic_UK02,26,10.2,28.5,45.6,322.95,795.0,294.45,"[37.2, 33.6, 28.2, 21.6, 34.8, 50.4, 201.0, 16..."
2,asic_UK03,25,4.799,19.197,22.196,34.194,79.187,14.997,"[52.791, 35.994, 77.387, 79.187, 4.799, 22.196..."
3,asic_UK04,20,13.0,15.0,20.0,34.75,82.0,19.75,"[16.0, 13.0, 22.0, 20.0, 17.0, 15.0, 72.0, 82...."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
6,asic_UK08,5,31.0,35.0,44.0,48.0,52.0,13.0,"[48.0, 44.0, 31.0, 52.0, 35.0]"

Distribution summary for column 'clonidine_iv_cont':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
1,asic_UK02,213,0.03,0.03,0.06,0.06,0.12,0.03,"[0.06, 0.04, 0.03, 0.12]"
2,asic_UK03,43,0.005,0.005,0.04,0.04,0.04,0.035,"[0.04, 0.028, 0.005]"
3,asic_UK04,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,9379,0.0,0.06,0.09,0.12,0.18,0.06,"[0.15, 0.12, 0.09, 0.07, 0.06, 0.04, 0.01, 0.0..."
6,asic_UK08,1536,0.0,0.75,2.0,2.0,3.5,1.25,"[1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 3.0, 0...."

Distribution summary for column 'compliance':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,2152,1.717347,52.202296,72.987245,130.316327,300.0,78.114031,"[127.2857142855, 69.40102040800001, 30.2051020..."
1,asic_UK02,3270,0.77,24.12,37.805,66.0,353.04,41.88,"[45.21, 39.23, 60.9, 73.16, 51.29, 58.15, 54.9..."
2,asic_UK03,6603,0.0,14.797,18.236,21.4925,59.752,6.6955,"[13.729, 12.449000000000002, 19.732, 22.05, 20..."
3,asic_UK04,2692,0.883,50.212,67.227,113.761,422.682,63.549,"[294.21, 170.642, 97.384, 62.275, 55.508, 53.2..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
6,asic_UK08,30,44.3,65.575,90.25,110.75,165.0,45.175,"[68.8, 44.3, 53.6, 44.9, 45.6, 51.2, 69.6, 60...."

Distribution summary for column 'core_temp':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,8632,21.2,36.5,37.3,37.8,39.6,1.3,"[36.5, 35.75, 36.9, 37.1, 37.2, 37.3, 37.0, 36..."
1,asic_UK02,1148,33.5,36.7,37.25,37.7,40.2,1.0,"[36.8, 37.5, 35.4, 35.1, 35.0, 34.9, 36.4, 36...."
2,asic_UK03,9397,19.364,36.567,37.067,37.6,40.6,1.033,"[38.4, 38.536, 38.9, 38.88, 38.44300000000001,..."
3,asic_UK04,5607,26.6,37.2,37.6,38.0,52.777,0.8,"[34.4, 35.2, 35.4, 35.6, 35.8, 36.2, 36.4, 36...."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,12009,0.0,36.6,37.0,37.5,40.1,0.9,"[36.9, 37.0, 37.2, 37.3, 37.4, 37.7, 37.6, 37...."
6,asic_UK08,367,34.3,36.9,37.1,37.3,38.4,0.4,"[37.5, 37.4, 37.6, 37.7, 37.9, 38.1, 38.3, 38...."

Distribution summary for column 'creatinine':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,130,22.100425,75.583453,108.734091,171.499298,878.712898,95.915845,"[28.288544, 22.100425, 30.940595, 34.476663, 8..."
1,asic_UK02,177,29.0,51.0,69.0,118.0,376.0,67.0,"[54.0, 45.0, 47.0, 61.0, 62.0, 52.0, 59.0, 51...."
2,asic_UK03,261,28.0,61.0,82.0,139.0,669.0,78.0,"[52.0, 51.0, 61.0, 68.0, 53.0, 73.0, 62.0, 41...."
3,asic_UK04,61,36.245,49.505,59.229,71.605,123.762,22.1,"[38.013000000000005, 37.129, 39.781, 67.185, 6..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,237,22.1,50.39,80.45,135.25,320.01,84.86,"[38.9, 43.32, 33.59, 44.2, 32.71, 34.48, 51.27..."
6,asic_UK08,53,53.93,68.95,81.33,106.08,627.65,37.13,"[97.24, 167.96, 106.08, 73.37, 88.4, 76.91, 81..."

Distribution summary for column 'delta_p':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,4371,-9.811814,10.190358,12.229432,15.287865,30.240838,5.097507,"[5.095954950637201, 9.1745810648895, 9.5135315..."
1,asic_UK02,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
2,asic_UK03,6582,0.0,9.4715,11.2695,14.276,24.619,4.8045,"[18.355, 18.573, 18.282, 15.173, 16.133, 11.42..."
3,asic_UK04,894,-6.118,9.178,11.216,12.237,24.983,3.059,"[11.216, 12.236, 9.177, 8.158, 10.197, 9.178, ..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,15804,0.0,6.33,7.33,9.37,23.8,3.04,"[9.73, 10.07, 10.0, 8.07, 8.0, 8.87, 9.67, 9.7..."
6,asic_UK08,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]

Distribution summary for column 'ecmo':

    hospital      n   min    q1 median    q3   max   iqr example_values
0  asic_UK00  10096   0.0   0.0    0.0   0.0   0.0   0.0          [0.0]
1  asic_UK02   6216   0.0   1.0    1.0   1.0   1.0   0.0     [0.0, 1.0]
2  asic_UK03    512   0.0   0.0    0.0   1.0   1.0   1.0     [0.0, 1.0]
3  asic_UK04      0  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>             []
4  asic_UK06      0  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>             []
5  asic_UK07   3432   0.0   1.0    1.0   1.0   1.0   0.0     [0.0, 1.0]
6  asic_UK08      0  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>             []

Distribution summary for column 'etco2':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,91,33.0,33.0,33.0,55.0,60.0,22.0,"[57.0, 60.0, 45.0, 48.0, 52.0, 55.0, 33.0]"
1,asic_UK02,1779,0.0,25.08,31.92,38.0,101.08,12.92,"[24.32, 30.4, 28.12, 25.08, 23.56, 28.88, 27.3..."
2,asic_UK03,6070,0.0,31.0,35.0,40.0,85.0,9.0,"[62.0, 37.0, 21.0, 25.0, 23.0, 19.0, 27.0, 31...."
3,asic_UK04,2496,0.0,270.022,307.525,337.527,487.539,67.505,"[285.02299999999997, 232.519, 292.522999999999..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,10821,0.0,31.67,39.33,45.67,68.67,14.0,"[23.5, 24.67, 26.67, 40.33, 34.0, 31.33, 30.67..."
6,asic_UK08,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]

Distribution summary for column 'fio2':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,5265,25.0,31.0,40.0,50.0,100.0,19.0,"[60.0, 40.0, 30.0, 35.0, 100.0, 25.0, 50.0, 99..."
1,asic_UK02,9114,20.0,40.0,50.0,60.0,100.0,20.0,"[40.0, 35.0, 30.0, 50.0, 45.0, 100.0, 90.0, 70..."
2,asic_UK03,6644,21.0,34.8,40.95,60.0,100.0,25.2,"[100.0, 99.5, 99.7, 99.8, 99.4, 99.3, 80.0, 85..."
3,asic_UK04,3105,21.0,30.0,31.0,42.0,100.0,12.0,"[40.5, 40.0, 98.0, 30.0, 29.0, 97.0, 93.0, 31...."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,15733,30.0,30.0,40.0,50.0,100.0,20.0,"[40.0, 36.67, 30.0, 70.0, 100.0, 80.0, 81.67, ..."
6,asic_UK08,572,21.0,21.0,21.0,30.0,100.0,9.0,"[60.0, 40.0, 100.0, 50.0, 38.33, 35.0, 64.0, 4..."

Distribution summary for column 'hematocrit':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,1180,18.3,24.8,27.0,29.7,57.4,4.9,"[39.7, 37.0, 32.8, 35.8, 29.9, 30.1, 29.4, 29...."
1,asic_UK02,323,16.0,23.0,25.0,28.0,40.0,5.0,"[20.0, 23.0, 17.0, 29.0, 24.0, 25.0, 26.0, 22...."
2,asic_UK03,385,13.6,19.3,21.6,25.5,49.4,6.2,"[30.0, 25.6, 27.0, 26.0, 27.200000000000006, 2..."
3,asic_UK04,149,19.6,24.6,27.5,31.2,39.3,6.6,"[25.3, 25.6, 22.7, 20.3, 24.7, 24.6, 26.6, 39...."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,2305,0.0,25.0,26.0,28.0,46.5,3.0,"[34.0, 32.0, 31.0, 30.1, 30.0, 29.0, 31.1, 33...."
6,asic_UK08,41,22.2,25.6,28.4,32.2,42.8,6.6,"[26.3, 22.2, 24.0, 25.6, 26.6, 24.3, 23.3, 24...."

Distribution summary for column 'hemoglobin':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,1044,3.78566,5.02686,5.46128,6.08188,11.60522,1.05502,"[8.005740000000001, 7.50926, 6.64042, 7.261019..."
1,asic_UK02,323,3.4,4.8,5.2,5.8,8.2,1.0,"[4.3, 5.1, 3.8, 6.8, 5.6, 5.7, 6.2, 5.8, 5.9, ..."
2,asic_UK03,385,2.3,4.1,4.5,5.3,10.5,1.2,"[6.1, 5.4, 5.6, 5.3, 5.5, 5.2, 4.8, 5.1, 4.7, ..."
3,asic_UK04,149,3.91,4.841,5.585,6.268,8.068,1.427,"[4.9030000000000005, 4.965, 4.468, 3.972, 4.71..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,157,0.0,5.71,6.08,6.33,9.68,0.62,"[6.45, 6.7, 6.58, 5.65, 5.15, 5.77, 5.96, 5.9,..."
6,asic_UK08,41,4.78,5.28,5.83,6.27,8.69,0.99,"[5.34, 5.03, 5.28, 5.52, 5.59, 4.84, 4.78, 5.0..."

Distribution summary for column 'ie_ratio':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,2580,0.31,1.1,1.3,1.9,16.3,0.8,"[3.5, 3.1, 4.2, 4.4, 1.2, 2.5, 5.6, 2.2, 1.9, ..."
1,asic_UK02,957,0.333333,0.588235,0.714286,1.0,3.0,0.411765,"[0.6666666666666666, 0.4347826086956522, 0.714..."
2,asic_UK03,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
3,asic_UK04,970,0.5,0.833,1.0,1.0,1.4,0.167,"[1.0, 0.769, 0.7140000000000001, 0.909, 1.4, 0..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,8231,0.5,1.0,1.0,1.5,2.9,0.5,"[1.0, 0.91, 0.97, 0.94, 1.51, 2.7, 0.75, 0.62,..."
6,asic_UK08,30,0.67,0.71,0.71,0.91,0.91,0.2,"[0.67, 0.91, 0.71]"

Distribution summary for column 'inr':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,184,0.9,1.06,1.145,1.21,1.46,0.15,"[1.18, 1.13, 1.1, 1.0, 1.06, 0.99, 0.96, 0.95,..."
1,asic_UK02,264,0.0,1.1075,1.21,1.46,4.44,0.3525,"[1.16, 1.29, 1.66, 1.11, 1.56, 1.43, 1.38, 1.2..."
2,asic_UK03,2,1.9,1.95,2.0,2.05,2.1,0.1,"[1.9, 2.1]"
3,asic_UK04,134,1.0,1.1,1.1,1.2,1.6,0.1,"[1.1, 1.2, 1.0, 1.3, 1.6, 1.5, 1.4]"
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,277,0.0,1.0,1.0,1.1,3.2,0.1,"[1.0, 1.1, 1.2, 1.3, 1.6, 0.9, 0.0, 0.95, 1.4,..."
6,asic_UK08,30,1.0,1.1,1.2,1.2,1.4,0.1,"[1.1, 1.2, 1.4, 1.0, 1.3]"

Distribution summary for column 'insp_pressure':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,5194,0.0000,14.271013,18.348446,22.425878,36.696892,8.154865,"[11.2142522285046, 15.2928783427569, 15.631828..."
1,asic_UK02,1822,7.1400,16.320000,20.390000,24.470000,64.240000,8.150000,"[23.45, 17.34, 16.32, 19.37, 18.35, 14.28, 15...."
2,asic_UK03,6603,11.2170,20.394000,23.453000,28.076000,37.074000,7.682000,"[33.651, 33.796, 35.146, 28.892, 29.499, 30.43..."
3,asic_UK04,2968,0.0000,12.236000,16.315000,19.374000,40.788000,7.138000,"[20.904, 18.355, 19.374, 20.394, 16.315, 17.33..."
4,asic_UK06,484,8.1576,19.374300,20.394000,23.453100,30.591000,4.078800,"[25.4925, 24.4728, 23.4531, 22.4334, 26.5122, ..."
5,asic_UK07,15805,0.0000,17.000000,19.370000,24.980000,36.030000,7.980000,"[20.05, 20.39, 18.35, 19.03, 19.37, 16.32, 13...."
6,asic_UK08,566,0.0000,14.280000,17.340000,19.370000,25.490000,5.090000,"[21.41, 17.34, 22.43, 15.3, 12.24, 18.35, 19.3..."

Distribution summary for column 'lactate_art':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,1027,0.3,0.7,0.9,1.2,6.5,0.5,"[0.8, 0.9, 1.1, 1.0, 2.1, 1.6, 2.3, 1.7, 1.2, ..."
1,asic_UK02,1237,0.4,1.1,1.5,2.1,23.0,1.0,"[0.9, 1.1, 0.8, 4.1, 3.3, 2.8, 1.8, 1.9, 1.2, ..."
2,asic_UK03,1391,0.3,1.1,1.7,3.3,21.0,2.2,"[1.0, 1.3, 2.2, 2.15, 2.1, 1.5, 1.7, 1.8, 1.4,..."
3,asic_UK04,661,0.4,0.7,0.9,1.2,8.5,0.5,"[0.6, 0.7, 0.5, 0.8, 0.4, 1.0, 0.9, 1.1, 1.6, ..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,1914,0.24,0.88,1.31,1.78,17.87,0.9,"[3.75, 2.28, 2.05, 1.86, 1.61, 1.3, 1.11, 0.98..."
6,asic_UK08,281,0.2,0.6,0.8,1.1,5.5,0.5,"[5.5, 3.2, 2.7, 2.2, 1.5, 1.0, 1.1, 1.3, 1.2, ..."

Distribution summary for column 'ldh':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,74,117.0,230.5,353.5,500.25,1556.0,269.75,"[519.0, 213.0, 251.0, 422.0, 456.0, 463.0, 438..."
1,asic_UK02,64,0.0,357.3,635.7,782.7,1512.0,425.4,"[753.6, 0.0, 339.6, 337.2, 370.8, 591.0, 511.8..."
2,asic_UK03,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
3,asic_UK04,142,110.0,187.0,247.5,295.75,503.0,108.75,"[193.0, 169.0, 160.0, 136.0, 170.0, 155.0, 183..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,37,379.0,607.0,725.0,1120.0,4155.0,513.0,"[844.0, 699.0, 786.0, 637.0, 441.0, 583.0, 596..."
6,asic_UK08,11,172.0,179.0,201.0,267.0,374.0,88.0,"[172.0, 178.0, 319.0, 346.0, 374.0, 179.0, 212..."

Distribution summary for column 'lipase':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,60,8.0,15.5,23.5,39.25,358.0,23.75,"[16.0, 14.0, 21.0, 30.0, 32.0, 34.0, 58.0, 65...."
1,asic_UK02,175,4.8,18.6,33.0,98.7,471.0,80.1,"[27.6, 15.6, 33.0, 19.2, 28.8, 14.4, 18.6, 16...."
2,asic_UK03,98,4.799,11.398,26.6955,66.589,1857.29,55.191,"[19.797, 13.798, 12.598, 15.597, 26.995, 10.19..."
3,asic_UK04,3,16.0,20.5,25.0,45.5,66.0,25.0,"[16.0, 66.0, 25.0]"
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,41,14.0,66.0,129.0,432.0,1739.0,366.0,"[57.0, 20.0, 16.0, 47.0, 80.0, 45.0, 49.0, 83...."
6,asic_UK08,9,0.0,22.0,34.0,80.0,189.0,58.0,"[19.0, 0.0, 34.0, 124.0, 189.0, 27.0, 22.0, 71..."

Distribution summary for column 'map':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,9734,0.0,68.0,75.0,85.0,186.0,17.0,"[80.0, 78.0, 87.0, 79.66666666666667, 75.0, 69..."
1,asic_UK02,2014,-21.0,72.0,81.0,90.0,345.0,18.0,"[101.67, 65.0, 81.0, 84.0, 54.0, 72.0, 52.0, 5..."
2,asic_UK03,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
3,asic_UK04,5489,-2.0,76.0,84.0,96.0,266.0,20.0,"[82.0, 60.0, 66.0, 90.0, 64.0, 78.0, 72.0, 76...."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,19578,-21.75,69.8,78.93,89.4,278.93,19.6,"[63.8, 77.13, 79.07, 79.73, 81.13, 80.2, 83.27..."
6,asic_UK08,3618,-17.0,76.0,84.0,92.0,311.0,16.0,"[81.0, 60.0, 70.0, 68.0, 52.0, 56.0, 47.0, 46...."

Distribution summary for column 'minutes_since_admit':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,11656,0.0,4365.00,10155.0,17145.00,41595.0,12780.0,"[0.0, 15.0, 30.0, 45.0, 60.0, 75.0, 90.0, 105...."
1,asic_UK02,19297,15.0,8295.00,25710.0,49830.00,87885.0,41535.0,"[15, 30, 45, 60, 75, 90, 105, 120, 135, 150]"
2,asic_UK03,21942,0.0,8388.75,21727.5,69461.25,151740.0,61072.5,"[0, 15, 30, 45, 60, 75, 90, 105, 120, 135]"
3,asic_UK04,12684,15.0,4770.00,9840.0,17415.00,31995.0,12645.0,"[15, 30, 45, 60, 75, 90, 105, 120, 135, 150]"
4,asic_UK06,10808,0.0,4410.00,10185.0,17475.00,42465.0,13065.0,"[0, 15, 30, 45, 60, 75, 90, 105, 120, 135]"
5,asic_UK07,20455,15.0,7680.00,15780.0,25575.00,51480.0,17895.0,"[15, 30, 45, 60, 75, 90, 105, 120, 135, 150]"
6,asic_UK08,4805,15.0,1830.00,4275.0,17535.00,35550.0,15705.0,"[15, 30, 45, 60, 75, 90, 105, 120, 135, 150]"

Distribution summary for column 'norepinephrine_iv_cont':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
1,asic_UK02,7679,0.01,0.04,0.06,0.11,1.0,0.07,"[0.03, 0.05, 0.04, 0.07, 0.08, 0.02, 0.35, 0.6..."
2,asic_UK03,448,1.093,4.545,6.364,7.255,12.727,2.71,"[10.927, 8.479, 7.255, 6.957999999999998, 6.36..."
3,asic_UK04,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,14678,0.0,0.03,0.11,0.24,1.93,0.21,"[0.02, 0.01, 0.0, 0.08, 0.11, 0.12, 0.09, 0.05..."
6,asic_UK08,2151,0.0,0.0,0.05,0.12,0.98,0.12,"[0.34, 0.32, 0.28, 0.25, 0.23, 0.21, 0.18, 0.1..."

Distribution summary for column 'pct':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,114,0.07,0.21,0.675,2.6025,43.0,2.3925,"[3.09, 2.46, 2.29, 2.42, 43.0, 24.7, 16.7, 7.0..."
1,asic_UK02,87,0.0,0.205,0.58,2.7,17.5,2.495,"[0.11, 0.18, 0.19, 0.28, 4.6, 3.95, 12.1, 11.6..."
2,asic_UK03,190,0.06,0.6725,2.53,7.405,51.9,6.7325,"[0.6, 1.1, 2.87, 8.88, 5.65, 5.84, 15.5, 3.26,..."
3,asic_UK04,25,0.06,0.08,0.12,0.4,8.18,0.32,"[0.15, 0.13, 0.11, 0.08, 0.12, 0.09, 0.1, 0.07..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,210,0.0,0.2125,0.755,2.195,388.0,1.9825,"[0.08, 0.14, 0.09, 0.07, 0.12, 0.13, 3.76, 2.9..."
6,asic_UK08,2,0.23,0.23,0.23,0.23,0.23,0.0,[0.23]

Distribution summary for column 'peep':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,4721,0.0000,6.118297,7.138013,8.919831,15.295743,2.801534,"[7.1380134908453, 5.0, 6.0, 6.1182972778674, 5..."
1,asic_UK02,1769,5.0000,7.000000,7.900000,10.000000,18.000000,3.000000,"[10.0, 9.3, 9.7, 9.6, 9.0, 8.1, 7.8, 8.3, 8.4,..."
2,asic_UK03,6582,0.0000,9.245750,10.197000,14.480000,20.002000,5.234250,"[15.296, 15.223, 16.865, 13.719, 13.366, 19.01..."
3,asic_UK04,3081,-8.1580,5.099000,5.099000,7.138000,15.296000,2.039000,"[5.099, 6.117999999999999, 2.039, 0.0, 4.079, ..."
4,asic_UK06,1901,-1.0197,6.118200,8.157600,9.483210,15.295500,3.365010,"[6.1182, 6.32214, 6.42411, 4.486680000000001, ..."
5,asic_UK07,15804,0.0000,9.990000,10.540000,14.000000,23.330000,4.010000,"[10.13, 10.2, 9.99, 9.52, 9.42, 9.48, 9.59, 9...."
6,asic_UK08,566,5.1000,5.100000,5.100000,8.160000,11.220000,3.060000,"[7.14, 6.12, 5.1, 9.18, 11.22, 8.16, 10.2, 7.3..."

Distribution summary for column 'pf_ratio':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,1145,55.20,170.444444,246.428571,329.545455,725.000,159.10101,"[95.0, 108.333333333, 85.714285714, 88.5714285..."
1,asic_UK02,837,38.85,146.810000,200.000000,271.880000,1710.000,125.07000,"[377.14, 383.57, 398.57, 430.71, 392.14, 390.0..."
2,asic_UK03,904,41.90,135.538500,201.909000,280.290750,633.333,144.75225,"[72.5, 41.9, 55.585, 59.05, 51.207, 159.425, 1..."
3,asic_UK04,1199,-3.00,241.000000,326.000000,397.000000,1479.000,156.00000,"[322.0, 330.0, 365.0, 487.0, 390.0, 397.0, 433..."
4,asic_UK06,543,52.50,217.500000,277.500000,345.000000,1170.000,127.50000,"[382.5, 277.5, 465.0, 472.5, 487.5, 495.0, 502..."
5,asic_UK07,1396,45.50,140.837500,213.425000,273.167500,909.170,132.33000,"[313.75, 252.25, 245.0, 222.75, 212.75, 373.25..."
6,asic_UK08,63,79.10,252.540000,316.000000,375.715000,464.290,123.17500,"[79.1, 368.0, 247.75, 235.14, 160.5, 427.5, 26..."

Distribution summary for column 'ph_art':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,519,7.093209,7.363969,7.438962,7.466192,7.593979,0.102224,"[7.459767964771492, 7.491466406836006, 7.51186..."
1,asic_UK02,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
2,asic_UK03,1403,6.62,7.303,7.375,7.427,7.582,0.124,"[7.055, 7.365, 7.376, 7.345, 7.37, 7.428, 7.42..."
3,asic_UK04,662,7.317,7.44125,7.466,7.481,7.6,0.03975,"[7.399, 7.382000000000001, 7.403, 7.474, 7.486..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,1937,0.0,7.37,7.43,7.46,7.62,0.09,"[7.43, 7.49, 7.48, 7.47, 7.46, 7.45, 7.41, 7.3..."
6,asic_UK08,282,7.2,7.42,7.46,7.49,7.64,0.07,"[7.28, 7.37, 7.39, 7.36, 7.42, 7.4, 7.35, 7.38..."

Distribution summary for column 'platelets':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,153,64.0,150.0,204.0,297.0,701.0,147.0,"[234.0, 273.0, 332.0, 373.0, 182.0, 151.0, 187..."
1,asic_UK02,323,8.0,93.0,150.0,209.0,562.0,116.0,"[211.0, 154.0, 91.0, 84.0, 82.0, 19.0, 63.0, 5..."
2,asic_UK03,385,1.0,26.0,94.0,200.0,1088.0,174.0,"[362.0, 266.0, 253.0, 205.0, 226.0, 202.0, 167..."
3,asic_UK04,149,81.0,181.0,265.0,398.0,720.0,217.0,"[452.0, 469.0, 414.0, 319.0, 321.0, 312.0, 327..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,238,0.0,122.75,202.5,343.75,1175.0,221.0,"[94.0, 89.0, 113.0, 112.0, 127.0, 156.0, 160.0..."
6,asic_UK08,55,54.0,145.5,207.0,367.0,705.0,221.5,"[331.0, 313.0, 291.0, 371.0, 158.0, 154.0, 184..."

Distribution summary for column 'propofol_iv_cont':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
1,asic_UK02,1949,0.0,200.0,250.0,300.0,600.0,100.0,"[300.0, 250.0, 200.0, 260.0, 220.0, 210.0, 150..."
2,asic_UK03,395,79.8,79.8,160.0,220.0,300.0,140.2,"[300.0, 220.0, 160.0, 87.09100000000002, 79.8]"
3,asic_UK04,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,3052,0.0,20.0,120.0,200.0,500.0,180.0,"[300.0, 170.0, 20.0, 0.0, 160.0, 180.0, 200.0,..."
6,asic_UK08,902,0.0,1.0,1.78,2.22,4.0,1.22,"[1.74, 1.52, 1.3, 1.96, 2.17, 1.73, 0.98, 0.65..."

Distribution summary for column 'ptt':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,195,20.3,26.85,29.8,38.75,79.9,11.9,"[28.5, 31.0, 34.3, 30.3, 33.9, 44.8, 36.4, 35...."
1,asic_UK02,467,0.0,43.7,50.0,57.35,133.4,13.65,"[25.1, 26.9, 31.0, 31.1, 32.9, 44.5, 42.9, 37...."
2,asic_UK03,369,22.7,30.5,35.5,50.7,132.5,20.2,"[26.6, 25.8, 26.8, 28.8, 28.1, 25.2, 27.5, 30...."
3,asic_UK04,135,18.0,21.0,22.0,25.0,61.0,4.0,"[23.0, 21.0, 24.0, 25.0, 27.0, 26.0, 22.0, 20...."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,161,0.0,23.0,28.0,39.0,101.0,16.0,"[20.0, 18.0, 22.0, 93.0, 76.0, 101.0, 42.0, 47..."
6,asic_UK08,30,19.0,26.0,28.0,33.0,44.0,7.0,"[27.0, 28.0, 33.0, 29.0, 23.0, 24.0, 26.0, 30...."

Distribution summary for column 'resp_rate':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,9870,0.0,16.0,19.5,24.0,48.0,8.0,"[26.0, 30.33333333333333, 30.66666666666667, 2..."
1,asic_UK02,2004,0.0,17.0,21.0,26.0,63.0,9.0,"[20.0, 14.0, 17.0, 12.5, 13.0, 18.0, 15.0, 16...."
2,asic_UK03,9673,0.0,17.0,20.533,25.533,91.5,8.533,"[21.0, 22.267, 39.267, 36.667, 27.6, 30.2, 31...."
3,asic_UK04,5996,0.0,16.0,19.0,22.0,91.0,6.0,"[16.0, 13.5, 14.0, 20.0, 20.5, 19.0, 15.0, 18...."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,15808,0.0,14.67,18.0,23.0,113.5,8.33,"[26.33, 15.0, 12.0, 11.33, 9.67, 10.33, 16.33,..."
6,asic_UK08,846,0.0,15.0,16.0,18.0,36.0,3.0,"[12.0, 19.0, 17.0, 36.0, 18.0, 27.0, 22.0, 18...."

Distribution summary for column 'sao2':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,1033,34.3,93.4,96.1,97.7,100.0,4.3,"[99.0, 99.2, 99.6, 95.5, 99.8, 91.8, 95.2, 89...."
1,asic_UK02,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
2,asic_UK03,1278,14.6,95.025,97.4,98.6,100.0,3.575,"[85.7, 78.0, 88.8, 88.95, 85.2, 99.5, 98.9, 90..."
3,asic_UK04,662,78.3,96.9,98.1,98.8,100.6,1.9,"[100.1, 98.6, 98.5, 99.1, 99.6, 99.0, 99.4, 99..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,1914,62.3,96.1,97.0,97.9,99.9,1.8,"[98.1, 97.6, 97.3, 96.8, 96.3, 98.5, 91.8, 90...."
6,asic_UK08,283,55.9,94.7,96.7,97.7,99.8,3.0,"[96.4, 97.9, 95.5, 99.1, 97.1, 99.5, 98.0, 95...."

Distribution summary for column 'sbp':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,9694,31.0,103.0,118.0,140.0,336.0,37.0,"[112.0, 111.33333333333331, 122.0, 109.0, 102...."
1,asic_UK02,2011,15.0,105.0,117.0,131.0,210.0,26.0,"[139.67, 91.0, 123.0, 110.0, 84.0, 106.0, 82.0..."
2,asic_UK03,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
3,asic_UK04,5489,2.0,119.0,132.0,145.0,268.0,26.0,"[134.0, 82.0, 96.0, 126.0, 98.0, 118.0, 124.0,..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,19578,-5.5,110.93,121.47,133.67,283.53,22.74,"[92.73, 105.33, 111.07, 112.73, 115.2, 116.6, ..."
6,asic_UK08,3612,-12.0,131.0,144.0,156.0,312.0,25.0,"[109.0, 73.0, 93.0, 90.0, 64.0, 69.0, 58.0, 59..."

Distribution summary for column 'spo2':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,8190,70.0,93.0,96.0,98.0,100.0,5.0,"[87.5, 86.0, 89.0, 89.5, 91.0, 92.0, 90.0, 83...."
1,asic_UK02,1964,71.0,97.0,100.0,100.0,100.0,3.0,"[84.0, 99.0, 100.0, 89.0, 95.0, 79.0, 91.0, 97..."
2,asic_UK03,9962,37.923,95.643,97.667,99.286,100.0,3.643,"[83.0, 85.4, 84.46700000000001, 77.571, 78.533..."
3,asic_UK04,6342,71.0,96.0,98.0,99.0,100.0,3.0,"[100.0, 99.0, 97.0, 99.5, 98.0, 95.0, 80.0, 94..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,19806,63.33,96.33,98.0,99.0,100.0,2.67,"[100.0, 99.67, 95.67, 95.33, 97.0, 96.33, 96.0..."
6,asic_UK08,4567,73.0,94.0,96.0,98.0,100.0,4.0,"[100.0, 99.0, 98.0, 96.0, 97.0, 97.5, 98.5, 99..."

Distribution summary for column 'spont_resp_rate':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,4582,0.0,0.0,1.25,14.0,46.0,14.0,"[10.0, 6.0, 18.0, 3.0, 5.0, 9.0, 13.0, 2.0, 7...."
1,asic_UK02,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
2,asic_UK03,7449,0.0,17.857,22.0,28.077,47.786,10.22,"[22.0, 27.231, 38.714, 36.786, 29.933000000000..."
3,asic_UK04,3000,0.0,0.0,15.0,20.0,42.0,20.0,"[0.0, 1.0, 4.0, 3.0, 9.0, 19.0, 13.0, 20.0, 16..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,15811,0.0,1.33,11.67,19.33,113.5,18.0,"[16.33, 0.0, 3.33, 9.67, 10.33, 10.67, 13.0, 1..."
6,asic_UK08,552,0.0,0.0,0.0,15.0,32.0,15.0,"[0.0, 7.0, 27.0, 19.0, 17.0, 4.33, 13.0, 5.0, ..."

Distribution summary for column 'sufentanil_iv_cont':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
1,asic_UK02,5652,5.0,10.0,20.0,30.0,80.0,20.0,"[20.0, 30.0, 40.0, 10.0, 15.0, 25.0, 7.5, 5.0,..."
2,asic_UK03,4541,2.495,5.0,7.5,15.0,50.0,10.0,"[50.0, 40.0, 20.0, 16.667, 10.0, 15.0, 17.273,..."
3,asic_UK04,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,14351,0.0,5.0,10.0,20.0,150.0,15.0,"[10.0, 15.0, 20.0, 12.5, 5.0, 3.75, 2.5, 2.25,..."
6,asic_UK08,2021,0.0,5.0,20.0,52.47,74.97,47.47,"[45.0, 59.98, 74.97, 63.72, 52.47, 48.73, 52.5..."

Distribution summary for column 'troponin':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,32,0.006,0.01575,0.023,0.05925,5.748,0.0435,"[0.014, 0.008, 0.006, 0.022, 0.025, 0.023, 0.0..."
1,asic_UK02,25,0.02,0.04,0.29,9.63,15.08,9.59,"[0.07, 0.11, 0.12, 0.16, 0.18, 1.35, 4.54, 5.5..."
2,asic_UK03,32,0.00773,0.031375,0.06095,0.1985,1.392,0.167125,"[0.421, 0.222, 0.0435, 0.0681, 0.0577, 0.0568,..."
3,asic_UK04,22,0.007,0.01625,0.041,0.47625,1.901,0.46,"[0.011, 0.016, 0.0069999999999999, 0.01, 0.057..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,89,0.01,0.17,0.46,1.37,6.2,1.2,"[0.01, 0.06, 0.04, 0.02, 0.71, 5.32, 4.42, 3.6..."
6,asic_UK08,3,0.33,0.375,0.42,0.52,0.62,0.145,"[0.42, 0.33, 0.62]"

Distribution summary for column 'urea':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,131,3.006,7.014,10.02,16.1155,42.585,9.1015,"[4.509, 3.841, 5.3439999999999985, 34.73600000..."
1,asic_UK02,177,0.9,6.3,8.5,11.6,33.5,5.3,"[11.1, 11.5, 12.6, 11.3, 12.0, 9.3, 8.4, 9.2, ..."
2,asic_UK03,254,1.3,6.1,9.45,13.55,32.5,7.45,"[11.3, 11.5, 12.0, 16.3, 10.6, 17.4, 11.2, 8.1..."
3,asic_UK04,60,1.837,3.841,5.2605,7.7655,13.694,3.9245,"[2.839, 2.338, 2.6719999999999997, 5.01, 5.343..."
4,asic_UK06,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,[]
5,asic_UK07,237,2.92,5.23,7.58,10.97,27.1,5.74,"[5.91, 5.9, 5.34, 3.71, 5.51, 4.49, 4.66, 6.38..."
6,asic_UK08,52,0.0,16.075,22.0,29.25,44.1,13.175,"[16.0, 30.0, 33.0, 21.0, 12.0, 13.0, 44.0, 34...."

Distribution summary for column 'vt_per_kg_ibw':

,hospital,n,min,q1,median,q3,max,iqr,example_values
0,asic_UK00,858,5.822485,6.248122,6.248122,6.496243,6.496243,0.248122,"[6.248121667474552, 6.36343788274136, 6.165414..."
1,asic_UK02,1842,0.000000,4.550000,6.295000,7.580000,28.940000,3.030000,"[7.42, 4.28, 4.95, 6.52, 6.3, 6.85, 5.87, 5.56..."
2,asic_UK03,7017,0.000000,5.075000,5.800000,6.698000,16.823000,1.623000,"[5.799, 5.2810000000000015, 8.705, 7.997000000..."
3,asic_UK04,3082,0.013000,6.645250,7.638000,8.981500,41.056000,2.336250,"[7.698, 9.138, 9.158, 8.738, 9.806, 9.253, 8.1..."
4,asic_UK06,1909,0.000000,8.643899,4769.172071,8785.602947,16978.252575,8776.959048,"[10063.463281, 10643.699002, 10752.4932, 11060..."
5,asic_UK07,15803,0.000000,5.000000,7.100000,8.520000,33.540000,3.520000,"[5.06, 7.84, 7.83, 7.88, 6.79, 7.45, 9.04, 10...."
6,asic_UK08,569,0.000000,5.800000,6.090000,6.370000,28.430000,0.570000,"[6.97, 3.3, 7.79, 7.55, 4.72, 5.46, 6.24, 1.09..."

**Cross-hospital distrbution mismatches:**
`norepinephrine_iv_cont`, `clonidine_iv_con`, `vt_per_kg_ibw`, `etco2`, `ie_ratio`, `lipase`, `pct`

## Harmonized Value Preview

Show a compact value preview for each harmonized hospital table.

In [13]:
for hospital, df in harmonized_tables.items():
    display(Markdown(f"### {hospital}"))
    display(value_preview(df))

### asic_UK00

,column,dtype,non_null_count,n_unique_non_null,example_values
0,hospital_id,string,11656,1,[asic_UK00]
1,stay_id,Int64,11656,10,"[372, 419, 1014, 1204, 1955, 2203, 2353, 2578,..."
2,time,string,11656,2774,"[0 days 00:00:00, 0 days 00:15:00, 0 days 00:3..."
3,minutes_since_admit,float64,11656,2774,"[0.0, 15.0, 30.0, 45.0, 60.0, 75.0, 90.0, 105...."
4,heart_rate,float64,9863,152,"[129.5, 135.0, 134.0, 126.33333333333331, 124...."
...,...,...,...,...,...
101,hydrocortisone_iv_bolus,float64,0,0,[]
102,prednisolone_iv_bolus,float64,0,0,[]
103,dexamethasone_iv_bolus,float64,0,0,[]
104,fludrocortisone_po_bolus,float64,0,0,[]
105,sofa,float64,0,0,[]

### asic_UK02

,column,dtype,non_null_count,n_unique_non_null,example_values
0,hospital_id,string,19297,1,[asic_UK02]
1,stay_id,Int64,19297,10,"[237, 334, 403, 440, 478, 506, 611, 723, ...]"
2,time,string,19297,5859,"[0 days 00:00:00, 0 days 00:15:00, 0 days 00:3..."
3,minutes_since_admit,int64,19297,5859,"[15, 30, 45, 60, 75, 90, 105, 120, ...]"
4,heart_rate,float64,2030,107,"[82.0, 83.0, 69.0, 77.0, 72.67, 74.0, 64.0, 87..."
...,...,...,...,...,...
101,hydrocortisone_iv_bolus,float64,1,1,[100.0]
102,prednisolone_iv_bolus,float64,0,0,[]
103,dexamethasone_iv_bolus,float64,0,0,[]
104,fludrocortisone_po_bolus,float64,0,0,[]
105,sofa,float64,0,0,[]

### asic_UK03

,column,dtype,non_null_count,n_unique_non_null,example_values
0,hospital_id,string,21942,1,[asic_UK03]
1,stay_id,Int64,21942,10,"[372, 419, 650, 728, 1014, 1204, 1221, 1258, ...]"
2,time,string,21942,10117,"[0 days 00:00:00, 0 days 00:15:00, 0 days 00:3..."
3,minutes_since_admit,int64,21942,10117,"[0, 15, 30, 45, 60, 75, 90, 105, ...]"
4,heart_rate,float64,9974,2433,"[139.0, 129.733, 141.214, 142.143, 128.667, 12..."
...,...,...,...,...,...
101,hydrocortisone_iv_bolus,float64,10117,2,"[0.0, 100.0]"
102,prednisolone_iv_bolus,float64,0,0,[]
103,dexamethasone_iv_bolus,float64,2323,3,"[0.0, 6.0, 2.0]"
104,fludrocortisone_po_bolus,float64,0,0,[]
105,sofa,float64,213,23,"[5.0, 8.0, 10.0, 7.0, 6.0, 3.0, 0.0, 4.0, ...]"

### asic_UK04

,column,dtype,non_null_count,n_unique_non_null,example_values
0,hospital_id,string,12684,1,[asic_UK04]
1,stay_id,Int64,12684,10,"[31, 82, 237, 271, 279, 334, 403, 427, ...]"
2,time,string,12684,2133,"[0 days 00:00:00, 0 days 00:15:00, 0 days 00:3..."
3,minutes_since_admit,int64,12684,2133,"[15, 30, 45, 60, 75, 90, 105, 120, ...]"
4,heart_rate,float64,6633,473,"[85.0, 96.0, 86.0, 80.0, 84.0, 82.0, 78.0, 90...."
...,...,...,...,...,...
101,hydrocortisone_iv_bolus,Float64,0,0,[]
102,prednisolone_iv_bolus,Float64,0,0,[]
103,dexamethasone_iv_bolus,Float64,0,0,[]
104,fludrocortisone_po_bolus,Float64,0,0,[]
105,sofa,Float64,0,0,[]

### asic_UK06

,column,dtype,non_null_count,n_unique_non_null,example_values
0,hospital_id,string,10808,1,[asic_UK06]
1,stay_id,Int64,10808,10,"[237, 334, 403, 440, 478, 506, 578, 604, ...]"
2,time,string,10808,2832,"[0 days 00:00:00, 0 days 00:15:00, 0 days 00:3..."
3,minutes_since_admit,int64,10808,2832,"[0, 15, 30, 45, 60, 75, 90, 105, ...]"
4,heart_rate,float64,0,0,[]
...,...,...,...,...,...
101,hydrocortisone_iv_bolus,float64,0,0,[]
102,prednisolone_iv_bolus,float64,0,0,[]
103,dexamethasone_iv_bolus,float64,0,0,[]
104,fludrocortisone_po_bolus,float64,0,0,[]
105,sofa,float64,0,0,[]

### asic_UK07

,column,dtype,non_null_count,n_unique_non_null,example_values
0,hospital_id,string,20455,1,[asic_UK07]
1,stay_id,Int64,20455,10,"[372, 419, 1014, 1204, 1221, 1258, 1304, 1934,..."
2,time,string,20455,3432,"[0 days 00:00:00, 0 days 00:15:00, 0 days 00:3..."
3,minutes_since_admit,int64,20455,3432,"[15, 30, 45, 60, 75, 90, 105, 120, ...]"
4,heart_rate,float64,20062,1622,"[66.4, 61.33, 57.53, 59.0, 58.13, 62.87, 59.4,..."
...,...,...,...,...,...
101,hydrocortisone_iv_bolus,float64,7,1,[100.0]
102,prednisolone_iv_bolus,float64,0,0,[]
103,dexamethasone_iv_bolus,float64,26,2,"[8.0, 40.0]"
104,fludrocortisone_po_bolus,float64,0,0,[]
105,sofa,float64,0,0,[]

### asic_UK08

,column,dtype,non_null_count,n_unique_non_null,example_values
0,hospital_id,string,4805,1,[asic_UK08]
1,stay_id,Int64,4805,10,"[237, 403, 478, 611, 723, 2074, 2142, 2316, ...]"
2,time,string,4805,2370,"[0 days 00:00:00, 0 days 00:15:00, 0 days 00:3..."
3,minutes_since_admit,int64,4805,2370,"[15, 30, 45, 60, 75, 90, 105, 120, ...]"
4,heart_rate,float64,4613,228,"[99.0, 100.0, 95.0, 105.0, 101.0, 107.0, 94.5,..."
...,...,...,...,...,...
101,hydrocortisone_iv_bolus,float64,251,3,"[8.4, 6.2, 4.0]"
102,prednisolone_iv_bolus,float64,0,0,[]
103,dexamethasone_iv_bolus,float64,1,1,[4.0]
104,fludrocortisone_po_bolus,float64,0,0,[]
105,sofa,float64,0,0,[]